# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-bigquery:dev
test_strictness_level: low
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_bigquery/spec.yaml"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "exception"
  discovery:
    tests:
      - config_path: "secrets/config.json"
        timeout_seconds: 100
      - config_path: "secrets/config_with_dataset.json"
        timeout_seconds: 100
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        empty_streams: []
        timeout_seconds: 100
        validate_stream_statuses: true
        expect_trace_message_on_failure: false
        expect_records:
          path: "integration_tests/expected_records.jsonl"
          exact_order: no
      - config_path: "secrets/cdc_config.json"
        configured_catalog_path: "integration_tests/cdc_configured_catalog.json"
        empty_streams: []
        timeout_seconds: 100
        validate_stream_statuses: true
        fail_on_extra_columns: false
        expect_trace_message_on_failure: false
        expect_records:
          path: "integration_tests/expected_records.jsonl"
          exact_order: no
  incremental: 
   tests:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/inc_configured_catalog.json"
      timeout_seconds: 100
      future_state:
        future_state_path: "integration_tests/inc_abnormal_state.json"
    - config_path: "secrets/cdc_config.json"
      configured_catalog_path: "integration_tests/cdc_configured_catalog.json"
      timeout_seconds: 100
      future_state:
        future_state_path: "integration_tests/cdc_abnormal_state.json"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        timeout_seconds: 100
      - config_path: "secrets/cdc_config.json"
        configured_catalog_path: "integration_tests/cdc_configured_catalog.json"
        timeout_seconds: 100
  connector_attributes:
    tests:
      - config_path: "secrets/config.json"
        timeout_seconds: 100
      - config_path: "secrets/cdc_config.json"
        timeout_seconds: 100