connector_image: airbyte/source-snowflake:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "integration_tests/expected_spec.json"
        config_path: "secrets/config.json"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
