connector_image: airbyte/source-snowflake:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "integration_tests/expected_spec.json"
        config_path: "secrets/config.json"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        expect_records:
          path: "integration_tests/expected_records.jsonl"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"